q=[1 0 0];
y=[0 1 0];
u=[1 1 0];
i=[1 0 1];
a=[1 1 1];
f=[i;i;a;i;i];
g=[a;q;a;q;a];
j=[q;q;q;q;a];
k=[a;i;i;i;a];
z=[i y;i y;i y;i y;a u];
x=[a;i;a;u;i];
c=[u;i;i;i;u];
v=[f g j j k z k x j c]
