q=[1 0 0];
t=[0 0 1];
y=[0 1 0];
u=[1 1 0];
i=[1 0 1];
p=[0 1 1];
a=[1 1 1];
s=[0 0 0];
f=[i;i;i;a;i;i;i];
g=[a;q;q;a;q;q;a];
j=[q;q;q;q;q;q;a];
k=[a;i;i;i;i;i;a];
z=[q y t;y i y;y i y;y i y;y i y;t s q;t s q];
x=[a a;q t;a a;i s;q q;q y;q t];
c=[u;i;i;i;i;i;u];
v=[f g j j k z k x j c]*111
